/**
 * Products REST API
 * RESTful API for Products
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ClientApi } from './clientApi';


export interface ShipmentApi { 
    name?: string;
    sender?: ClientApi;
    shipmentId?: number;
}